# Offline tests for `s3_sign_url`. These pin the clock with Mocking so the
# generated URLs are deterministic and can be compared byte for byte.

using URIs: URI, queryparams

# The v2 query string is built from a `Dict`, whose iteration order is not
# stable across Julia versions, so v2 URLs are compared with the query
# parameters treated as an unordered set.
function url_parts(url)
    uri = URI(url)
    return (uri.scheme, uri.host, uri.path, queryparams(uri))
end

@testset "sign_url" begin
    creds = AWSCredentials(
        "AKIAIOSFODNN7EXAMPLE", "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY", ""
    )
    fixed_now = DateTime(2013, 5, 24, 0, 0, 0)
    patch = @patch Dates.now(::Type{Dates.UTC}) = fixed_now

    @testset "HMAC helpers" begin
        # RFC 2202 test case 2 (HMAC-SHA1)
        @test bytes2hex(AWSS3._hmac_sha1("Jefe", "what do ya want for nothing?")) ==
            "effcdf6ae5eb2fa2d27416d5f184df9c259a7c79"

        # AWS SigV4 signing key derivation and signature, from the worked
        # "GET Object" example in the Amazon S3 documentation:
        # https://docs.aws.amazon.com/AmazonS3/latest/API/sig-v4-header-based-auth.html
        key_date = AWSS3._hmac_sha256("AWS4" * creds.secret_key, "20130524")
        key_region = AWSS3._hmac_sha256(key_date, "us-east-1")
        key_service = AWSS3._hmac_sha256(key_region, "s3")
        key_signing = AWSS3._hmac_sha256(key_service, "aws4_request")
        string_to_sign = join(
            [
                "AWS4-HMAC-SHA256",
                "20130524T000000Z",
                "20130524/us-east-1/s3/aws4_request",
                "7344ae5b7ee6c3e7e6b0fe0640412a37625d1fbfff95c48bbb2dc43964946972",
            ],
            "\n",
        )
        @test bytes2hex(AWSS3._hmac_sha256(key_signing, string_to_sign)) ==
            "f0e8bdb87c964420e857bd35b5d6ed310bd44f0170aba48dd91039c6036bdb41"
    end

    # Full URLs with the clock pinned. The expected strings were generated by the
    # previous implementation of these functions for the same inputs, so this
    # guards against any change in the signature or in the URL layout.
    @testset "v4" begin
        apply(patch) do
            config = AWSConfig(; creds, region="us-east-1")
            @test s3_sign_url(config, "examplebucket", "dir/test file.txt") ==
                "http://s3.amazonaws.com/examplebucket/dir/test%20file.txt?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAIOSFODNN7EXAMPLE%2F20130524%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20130524T000000Z&X-Amz-Expires=3600&X-Amz-Security-Token=&X-Amz-SignedHeaders=host&X-Amz-Signature=8f554065d19c1853885c9d53fa285c83212c3fb49d7b060cca3d7abc0c09fab4"
            @test s3_sign_url(
                config,
                "examplebucket",
                "dir/test file.txt",
                600;
                verb="PUT",
                protocol="https",
            ) ==
                "https://s3.amazonaws.com/examplebucket/dir/test%20file.txt?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAIOSFODNN7EXAMPLE%2F20130524%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20130524T000000Z&X-Amz-Expires=600&X-Amz-Security-Token=&X-Amz-SignedHeaders=host&X-Amz-Signature=1339f1422de49a996fc2cb02589ae7735b4180969394034789b27a5eeaeefa95"

            config_tok = AWSConfig(;
                creds=AWSCredentials(creds.access_key_id, creds.secret_key, "TOKEN123"),
                region="eu-west-1",
            )
            @test s3_sign_url(config_tok, "examplebucket", "dir/test file.txt") ==
                "http://s3-eu-west-1.amazonaws.com/examplebucket/dir/test%20file.txt?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAIOSFODNN7EXAMPLE%2F20130524%2Feu-west-1%2Fs3%2Faws4_request&X-Amz-Date=20130524T000000Z&X-Amz-Expires=3600&X-Amz-Security-Token=TOKEN123&X-Amz-SignedHeaders=host&X-Amz-Signature=9e47aa81792a0eff6b66da47db1fa0c924b488c9cb6979ab9a53e9587158ba76"
            @test s3_sign_url(
                config_tok,
                "examplebucket",
                "dir/test file.txt",
                600;
                verb="PUT",
                protocol="https",
            ) ==
                "https://s3-eu-west-1.amazonaws.com/examplebucket/dir/test%20file.txt?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAIOSFODNN7EXAMPLE%2F20130524%2Feu-west-1%2Fs3%2Faws4_request&X-Amz-Date=20130524T000000Z&X-Amz-Expires=600&X-Amz-Security-Token=TOKEN123&X-Amz-SignedHeaders=host&X-Amz-Signature=67c76e94b45b95ba0edf6e0bb093b51f95b85ac389adc1de2feef1c3ae6aced1"
        end
    end

    @testset "v2" begin
        apply(patch) do
            config = AWSConfig(; creds, region="us-east-1")
            @test url_parts(
                s3_sign_url(
                    config, "examplebucket", "dir/test file.txt"; signature_version="v2"
                ),
            ) == url_parts(
                "http://examplebucket.s3.us-east-1.amazonaws.com/dir/test%20file.txt?Expires=1369357200&response-content-disposition=attachment&Signature=IzwhOB%2BYDj4mZ4tBzwyKgT8gI%2FE%3D&AWSAccessKeyId=AKIAIOSFODNN7EXAMPLE&x-amz-security-token=",
            )
            @test url_parts(
                s3_sign_url(
                    config,
                    "examplebucket",
                    "dir/test file.txt",
                    600;
                    verb="PUT",
                    protocol="https",
                    signature_version="v2",
                ),
            ) == url_parts(
                "https://examplebucket.s3.us-east-1.amazonaws.com/dir/test%20file.txt?Expires=1369354200&response-content-disposition=attachment&Signature=7YxZsJ2bNttk6qLYrX0Ua%2BzSFUs%3D&AWSAccessKeyId=AKIAIOSFODNN7EXAMPLE&x-amz-security-token=",
            )

            config_tok = AWSConfig(;
                creds=AWSCredentials(creds.access_key_id, creds.secret_key, "TOKEN123"),
                region="eu-west-1",
            )
            @test url_parts(
                s3_sign_url(
                    config_tok, "examplebucket", "dir/test file.txt"; signature_version="v2"
                ),
            ) == url_parts(
                "http://examplebucket.s3.eu-west-1.amazonaws.com/dir/test%20file.txt?Expires=1369357200&response-content-disposition=attachment&Signature=RQszMIU%2BaN6FLg6TqZbPKEWtJtE%3D&AWSAccessKeyId=AKIAIOSFODNN7EXAMPLE&x-amz-security-token=TOKEN123",
            )
            @test url_parts(
                s3_sign_url(
                    config_tok,
                    "examplebucket",
                    "dir/test file.txt",
                    600;
                    verb="PUT",
                    protocol="https",
                    signature_version="v2",
                ),
            ) == url_parts(
                "https://examplebucket.s3.eu-west-1.amazonaws.com/dir/test%20file.txt?Expires=1369354200&response-content-disposition=attachment&Signature=k%2FdQaeCBc%2BsCkH2O9f8Ux520xRs%3D&AWSAccessKeyId=AKIAIOSFODNN7EXAMPLE&x-amz-security-token=TOKEN123",
            )
        end
    end
end
