language: julia
os:
  - linux
  - osx
julia:
  - 1.0  # LTS
  - 1    # Latest release
  - nightly
notifications:
  email:
    recipients:
      - nightly-dev@invenia.ca
    on_success: never
    on_failure: always
    if: type = cron
env:
  global:
  - secure: J0CVnhWwna0uXG8LFUjuBIT/meX/d1xiJL6Qme1uJc4sGhj+hVo3ULREZDatsLGEBmYLrtxZXvTG4FzIwQ5NvSnZbXKpbnMVeMTn8Z1VAO7ki2MjrrHsK09WvHr6SwYuQdhSO77/wnIP5+SLIUXNoEPr/o/EJqa5OQmqY2JBAxovKVDNkxLkI+bFOBnSDH/1FJe5/wLlCLK31ixuQ4K2lvYjSHGiex+r1NWvr6NNvBnE4xCqgfHYRcfEIrM+xFRlX5PLG+I824uvs2kS74sL6+lAxn/4ceFsqVVrB2xuvTScimMAn5e8Ikxl8xPI5ESRwNH/oQj7l3GAZ5sv7Z4VqRIxqTs6XFEwDuK1zDVeQFEKHgdchdC0zB3rEOVdroC6dFiHCbDyYErXfXjjOhZosd60vqJ5B9828HQE8w/iLSGSYCIMbLLMpo447TckZlN9UTrbl9Y2eLbiYy0Kj9PTaWsPvZAZpHfUqXK9iz/HEw1kby4mUVYxkvlDZhq3/ITEu9tPJqN23p4RLCO4/OPW2YER4nTuF/kIydnPW7Bju6h/LapWpr+dsGuaC4PmY6h4fecvlFQEHaLbfyoN0lEsfwUkaVr8OCWRkrxmcumyOuvNlfA2f7BxzOURvzYUzdswCOHPMU2+CYBmSuKCyjMgPkoSVpNiPgQKEXZawNTur2E=
  - secure: BZ8ZcWyFwwVW3xlMvv1Tzoar4apaxlaVrNcrjn8fxNsj2oCYrxRrtwjnUS7MRR2Tag/aEWs1m0dmyod3XcGPAc7+5xPIX6gCWwtKzvO7WvZsMoMzRqYaphRXfY/jc8MA/Cl8dnjavE0lCKohVXTnPHkFgcObxqqkp5Ll0hyOmEvwRls12FWrSg2g3utJ5GESSmTLEgoM3iVLP32+UOTKlOOzpRFdKe+IbSYfT03Tv1Vyj83waORux0xtZwdcuRsy/JI96DKkvCTNuaie0IOZI9V8h7WBgUjjXR6ScsecWwueRr63rFzgJzFyolNjOAbYGtGImhjfLVmYb0juG7m391q7dV5kNAy51xKGLNk7tni6q7Tvxlwzc/WPo/9xkwM1dvtX8lAvOL/aAPe/UGBCh8Wlo1awjQ/gyYvx+GKM969z6ZKoqBJMtIeUSvOvdaXudFvwtg9ky60YYfaTgIZqdPt3j93CUd/PgRM2aL4O7LrGJzrLe8/l44KZajmy+A2p3la344HuaT3MnH2iAasaYiyeENjpb6R8mU37YNBVgH5hCYn4goj14IHmqAf6uuaoam4M5SNYWbcQymEIq1O+HzBdir8x8S7hzJW+nwwnehAY97AljqwJaAaUcjoBjI7OkIX7LrdtquVoO075BHjc0N46B9fpDpLxCTIGjBGJ6h8=
matrix:
  allow_failures:
  - julia: nightly
