name: CompatHelper

on:
  schedule:
    - cron: '00 00 * * *'

jobs:
  CompatHelper:
    runs-on: ubuntu-latest
    steps:
      - uses: julia-actions/setup-julia@v2
        with:
          version: "1.6"
      - uses: julia-actions/cache@v2
      - name: Install CompatHelper
        shell: julia --project=@compat --color=yes {0}
        run: |
          using Pkg
          Pkg.add(PackageSpec(; name="CompatHelper", version="1"))
      - name: Run CompatHelper
        shell: julia --project=@compat --color=yes {0}
        run: |
          using CompatHelper
          CompatHelper.main()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
